//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.454
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paper.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Paper.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static System.Drawing.Bitmap Circle {
            get {
                object obj = ResourceManager.GetObject("Circle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;COLLADA xmlns=&quot;http://www.collada.org/2005/11/COLLADASchema&quot; version=&quot;1.4.1&quot;&gt;
        ///  &lt;asset&gt;
        ///    &lt;contributor&gt;
        ///      &lt;author&gt;Geff&lt;/author&gt;
        ///      &lt;authoring_tool&gt;Papier Level Editor&lt;/authoring_tool&gt;
        ///    &lt;/contributor&gt;
        ///    &lt;created&gt;{DATETIME}&lt;/created&gt;
        ///    &lt;modified&gt;{DATETIME}&lt;/modified&gt;
        ///    &lt;unit name=&quot;meter&quot; meter=&quot;1&quot;/&gt;
        ///    &lt;up_axis&gt;Z_UP&lt;/up_axis&gt;
        ///  &lt;/asset&gt;
        ///  &lt;library_images/&gt;
        ///  &lt;library_geometries&gt;
        ///{MODEL}
        ///      &lt;geometry id=&quot;{FOLDING_NAME}-mesh&quot; name=&quot;{FO [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        public static string COLLADA_Exporter_Template_Papier {
            get {
                return ResourceManager.GetString("COLLADA_Exporter_Template_Papier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;COLLADA xmlns=&quot;http://www.collada.org/2005/11/COLLADASchema&quot; version=&quot;1.4.1&quot;&gt;
        ///  &lt;asset&gt;
        ///    &lt;contributor&gt;
        ///      &lt;author&gt;Geff&lt;/author&gt;
        ///      &lt;authoring_tool&gt;Papier Level Editor&lt;/authoring_tool&gt;
        ///    &lt;/contributor&gt;
        ///    &lt;created&gt;{DATETIME}&lt;/created&gt;
        ///    &lt;modified&gt;{DATETIME}&lt;/modified&gt;
        ///    &lt;unit name=&quot;meter&quot; meter=&quot;1&quot;/&gt;
        ///    &lt;up_axis&gt;Z_UP&lt;/up_axis&gt;
        ///  &lt;/asset&gt;
        ///  &lt;library_images/&gt;
        ///  &lt;library_geometries&gt;
        ///{MODEL}
        ///      &lt;geometry id=&quot;{FOLDING_NAME}-mesh&quot; name=&quot;{FO [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        public static string COLLADA_Exporter_Template_Papier2 {
            get {
                return ResourceManager.GetString("COLLADA_Exporter_Template_Papier2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ; FBX 6.1.0 project file
        ///; Export Papier - Geff
        ///; ----------------------------------------------------
        ///
        ///FBXHeaderExtension:  {
        ///	FBXHeaderVersion: 1003
        ///	FBXVersion: 6100
        ///	CreationTimeStamp:  {
        ///		Version: 1000
        ///		Year: {YEAR}
        ///		Month: {MONTH}
        ///		Day: {DAY}
        ///		Hour: {HOUR}
        ///		Minute: {MINUTE}
        ///		Second: {SECOND}
        ///		Millisecond: {MILLISECOND}
        ///	}
        ///	Creator: &quot;FBX PAPIER&quot;
        ///	OtherFlags:  {
        ///		FlagPLE: 0
        ///	}
        ///}
        ///CreationTime: &quot;{DATETIME}&quot;
        ///Creator: &quot;PAPIER&quot;
        ///
        ///; Object definitions
        ///;----------------------- [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        public static string FBX_Exporter_Template_Papier {
            get {
                return ResourceManager.GetString("FBX_Exporter_Template_Papier", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap Grid {
            get {
                object obj = ResourceManager.GetObject("Grid", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap GridH {
            get {
                object obj = ResourceManager.GetObject("GridH", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap GridV {
            get {
                object obj = ResourceManager.GetObject("GridV", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Icon_CuttingZoneH {
            get {
                object obj = ResourceManager.GetObject("Icon_CuttingZoneH", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Icon_CuttingZoneV {
            get {
                object obj = ResourceManager.GetObject("Icon_CuttingZoneV", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Icon_Folding {
            get {
                object obj = ResourceManager.GetObject("Icon_Folding", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Icon_Grid {
            get {
                object obj = ResourceManager.GetObject("Icon_Grid", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Icon_Link {
            get {
                object obj = ResourceManager.GetObject("Icon_Link", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Icon_MovingZoneH {
            get {
                object obj = ResourceManager.GetObject("Icon_MovingZoneH", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Icon_MovingZoneV {
            get {
                object obj = ResourceManager.GetObject("Icon_MovingZoneV", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Icon_Platform {
            get {
                object obj = ResourceManager.GetObject("Icon_Platform", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Icon_SensorButton {
            get {
                object obj = ResourceManager.GetObject("Icon_SensorButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Icon_SensorCamera {
            get {
                object obj = ResourceManager.GetObject("Icon_SensorCamera", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Icon_SensorNearness {
            get {
                object obj = ResourceManager.GetObject("Icon_SensorNearness", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Icon_SensorRemoteControl {
            get {
                object obj = ResourceManager.GetObject("Icon_SensorRemoteControl", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Move {
            get {
                object obj = ResourceManager.GetObject("Move", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Resize {
            get {
                object obj = ResourceManager.GetObject("Resize", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
